steps:
  - id: "build image"
    name: "gcr.io/cloud-builders/docker"
    args: [ "build", "-t", "europe-docker.pkg.dev/${PROJECT_ID}/${_SERVICE_NAME}/${_SERVICE_NAME}:${_PR_NUMBER}-${SHORT_SHA}", "--target", "production", "." ]

  - id: "push image"
    name: "gcr.io/cloud-builders/docker"
    args: [ "push", "europe-docker.pkg.dev/${PROJECT_ID}/${_SERVICE_NAME}/${_SERVICE_NAME}:${_PR_NUMBER}-${SHORT_SHA}" ]

  - id: "deploy revision with tag"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "${_SERVICE_NAME}"
      - "--platform"
      - "managed"
      - "--region"
      - "${_REGION}"
      - "--image"
      - "europe-docker.pkg.dev/${PROJECT_ID}/${_SERVICE_NAME}/${_SERVICE_NAME}:${_PR_NUMBER}-${SHORT_SHA}"
      - "--tag"
      - "pr-${_PR_NUMBER}"
      - "--no-traffic"

  - id: "link revision on pull request"
    name: "europe-docker.pkg.dev/${PROJECT_ID}/utilities/deployment-preview"
    args:
      - "set"
      - "--project-id"
      - "${PROJECT_ID}"
      - "--region"
      - "${_REGION}"
      - "--service"
      - "${_SERVICE_NAME}"
      - "--pull-request"
      - "${_PR_NUMBER}"
      - "--repo-name"
      - "${_GITHUB_REPO}"
      - "--commit-sha"
      - "${SHORT_SHA}"
    secretEnv:
      - "GITHUB_TOKEN"

substitutions:
  _REGION: "europe-central2"
  _SERVICE_NAME: "site-cms"
  _GITHUB_REPO: "$(pull_request.pull_request.base.repo.full_name)"

availableSecrets:
  secretManager:
    - versionName: "projects/$PROJECT_ID/secrets/github_token/versions/latest"
      env: "GITHUB_TOKEN"
